# Generated by Django 4.0.5 on 2022-06-23 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_data_de_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.IntegerField()),
                ('salario', models.IntegerField()),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
