# Generated by Django 4.0.4 on 2022-06-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0003_cliente_nome'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.IntegerField()),
                ('Forma_De_Pagamento', models.CharField(choices=[('C', 'CHEQUE'), ('B', 'BOLETO'), ('D', 'DEPOSITO'), ('T', 'TRANSFERÊNCIA')], max_length=1)),
                ('Parcelas_Do_Pagamento', models.CharField(choices=[('1', '1x/ Sem Juros'), ('2', '2x/ Sem Juros'), ('3', '3x/ Sem Juros'), ('4', '4x/ Sem Juros'), ('5', '5x/ Sem Juros'), ('6', '6x/ Sem Juros'), ('7', '7x/ Sem Juros'), ('8', '8x/ Sem Juros'), ('9', '9x/ Sem Juros'), ('10', '10x/ Sem Juros'), ('11', '11x/ Sem Juros'), ('12', '12x/ Sem Juros')], max_length=2)),
                ('Data_Do_Pagamento', models.DateTimeField()),
                ('banco', models.CharField(max_length=15)),
                ('agencia', models.CharField(max_length=15)),
                ('conta', models.CharField(max_length=15)),
                ('data_de_nascimento', models.DateField()),
                ('Imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovei')),
                ('Nome_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
    ]
