# Generated by Django 4.0.4 on 2022-06-23 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='data_de_nascimento',
        ),
    ]
