# Generated by Django 4.0.4 on 2022-06-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
    ]
